### ISSUE TITLE
Add cookie deadline time to source code for not showing Terms of use twice for users

### ISSUE THREAD

**Issue by mraahemi** [CANBeWell/web#37]

**Comment by 0Calories** [comment]
Terms and conditions acceptance must be saved as a cookie, as well as profile data.

**Comment by mraahemi** [comment]
For any entrance, get cookies if they exist and set value and skip accept if they all exist.
Otherwise, show accept.
if patient: yes / provider: no
for gender: Male/ Female / Both
for age: A number between 18 to 149
for allAges: a boolean
For accept: a boolean
Next time the user comes to the web application if there was a cookie without value there should be a new cookie set otherwise the values should be called from previous cookies.
